# Generated by Django 5.1.6 on 2025-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsystem',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referralsystem',
            name='referral',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
