# Generated by Django 5.1.6 on 2025-03-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_referralsystem_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferralSystem',
            new_name='Referral',
        ),
    ]
