# Generated by Django 5.1.6 on 2025-03-30 06:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_rename_referralsystem_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraluser',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
