# Generated by Django 5.1.6 on 2025-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_referraluser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraluser',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
